### ISSUE TITLE
No titles on MacOS

### ISSUE THREAD

**Issue by ianobermiller** [ActivityWatch/aw-watcher-window#28]
Not sure if this is a known issue, but the window watcher always reports empty titles for MacOS (Sierra). I'd be happy to help debug, I'd like to get involved with ActivityWatch development.

**Comment by exoji2e** [comment]
Which commits are you running? This has not happened to me, however I'm on MacOs El Capitan.

**Comment by ianobermiller** [comment]
I was running the latest release, 0.7.1. However, I also tried this with master, and it is the same. I've been playing around with an updated AppleScript that does what I want. The problem may also be the apps I use, primarily Chrome, Atom, and iTerm.

**Comment by ianobermiller** [comment]
Ok, that took entirely too long. The issue was that I had moved the app around, and ended up with the accessibility permissions disabled.

**Comment by ErikBjare** [comment]
Hi there @ianobermiller. Happy to see you figured it out, and thanks a bunch for the PRs!

Your contributions are highly appreciated, let me know if you need help with anything 😃

**Comment by imeed166** [comment]
Hi, i have the same problem with activitywatch 0.9.0 on mac os catalina 10.15.6 and i have accesibility permission enabled for the app and the terminal.

**Comment by imeed166** [comment]
![image](https://user-images.githubusercontent.com/38974541/92388487-4012d180-f10f-11ea-9903-dd117df32d42.png)
