### ISSUE TITLE
exclude_title does not seem to be respected on Windows 10

### ISSUE THREAD

**Issue by yk64** [ActivityWatch/aw-watcher-window#38]
My aw-watcher-window.ini is as follows but still window titles are sent to the server.
I tried both aw-qt.exe and aw-watcher-window.exe but I got the same result.
```
[aw-watcher-window]
poll_time = 10.0
exclude_title = yes

[aw-watcher-window-testing]
poll_time = 1.0
exclude_title = yes
```
ActivityWatch Version: v0.8.0b9 
OS: Windows 10 Pro
Config path: C:\Users\user\AppData\Local\activitywatch\activitywatch\aw-watcher-window\aw-watcher-window.ini

**Comment by ErikBjare** [comment]
I believe that we haven't yet made a release that includes the PR (#37) which adds it as a configuration option. It should be out within a week or two!

**Comment by johan-bjareholt** [comment]
Should work in the latest release now! :)
