### ISSUE TITLE
[macOS] watcher unable to get name of current app if it has no dock icon

### ISSUE THREAD

**Issue by 8bitgentleman** [ActivityWatch/aw-watcher-window#43]
I just noticed that aw-watcher-window seems to be unable to get the current app name if the app has no icon in the dock. Specifically I noticed with [this app](https://plexamp.com/) which has the option to keep running while hiding the dock icon. With the icon hidden aw-watcher-window does not identify that the app is being used  and only records a generic "Google Chrome" event ([I believe it's made using react-native-web, which itself uses Electron?](https://medium.com/plexlabs/plexamp-v3-9af3b10063b4)) .

<img width="889" alt="Screen Shot 2020-04-16 at 3 51 08 PM" src="https://user-images.githubusercontent.com/4028391/79500341-46869c80-7ffa-11ea-8031-6d6b11efd813.png">

**Comment by iloveitaly** [comment]
The culprit is this code: `set frontApp to first application process whose frontmost is true`. It doesn't report menu bar applications. A quick StackOverflow search didn't seem to indicate there was a workaround.

**Comment by 8bitgentleman** [comment]
@iloveitaly just confirmed this has been fixed! Thanks for the ping
