### ISSUE TITLE
Support configuration of aw-server host+port

### ISSUE THREAD

**Issue by kamaradclimber** [ActivityWatch/aw-watcher-window#47]
This binary seems to assume the aw-server is running on localhost:5600.
If aw-server runs on a different machine, it would be convenient to allow configuration of hostname and port of the server.

**Comment by johan-bjareholt** [comment]
This is described in the documentation, it's configurable in the aw-client config.

https://docs.activitywatch.net/en/latest/getting-started.html?highlight=host#config

**Comment by kamaradclimber** [comment]
Indeed, I'm sorry I misread the documentation.
