### ISSUE TITLE
Being in the Desktop of Windows reports title as empty

### ISSUE THREAD

**Issue by watertrainer** [ActivityWatch/aw-watcher-window#48]
Basically the title. I noticed these Events popping up in my uncategorized and think this is the windows desktop.
![grafik](https://user-images.githubusercontent.com/47402928/98405874-4967de00-206d-11eb-9a7d-4537743d4aaf.png)

So I tried being on the desktop for 30s and looked at the raw buckets. It only showed explorer.exe without a title for the time on Desktop.
![grafik](https://user-images.githubusercontent.com/47402928/98406092-a5326700-206d-11eb-99a1-b307e4a5bf0a.png)

Is this a bug, intended or can this be fixed? Maybe a Special Case to add something to the title? I would just like to filter it out and add it to my Misc Category, so it doesn't always show such a high time of Uncategorized Activity

**Comment by ErikBjare** [comment]
You might be able to filter it out with the regular expression for an empty string: `^$` 

Where `^` will match the start of the string, and `$` will match the end of the string.

**Comment by watertrainer** [comment]
That works, thanks
