### ISSUE TITLE
MacOS: Use realtime accessibility notifications to improve precision and performance

### ISSUE THREAD

**Issue by modderme123** [ActivityWatch/aw-watcher-window#67]
While writing https://github.com/CM-Tech/timeviewer/blob/main/monitor/TimeViewer/AppDelegate.swift, I discovered the swift functions `AXObserverCreate` and `AXObserverAddNotification`. This allows the application to extremely efficiently respond to things like title changes while using almost no CPU (in comparison to the 3% that polling uses on my machine). Would it be possible to use something like this in ActivityWatch to prevent polling?

If this is something that you would be interested in, I'd be open to helping take this on

**Comment by ErikBjare** [comment]
This looks promising! I'd for sure be interested if exploring this. If you can take it on, I'd love that! (and I can make funds available upon request, if that's motivating)

I'd like @iloveitaly's comments on this, as he's been messing in that code the most recently, and has more recent experience with macOS than me :)

**Comment by iloveitaly** [comment]
@modderme123 I've been working on some of the [performance issues here](https://github.com/ActivityWatch/aw-watcher-window/pull/65) (I have it running locally and it's dropped CPU usage quite a bit). 

I think your approach would be way better! Do you think this is something that could be implemented with pyobjc? Or do we need native objc/swift here? I say submit a PR with this change as an alternative (not a replacement) for existing implementation so we can get some folks to test it.

**Comment by modderme123** [comment]
It's likely possible to implement using pyobjc, but I plan to implement it with swift because the above code is already pretty close (once compiled to the command line and converted to heartbeats).
