### ISSUE TITLE
Is it possible to replace aw-watcher-window?

### ISSUE THREAD

**Issue by flexagoon** [ActivityWatch/aw-watcher-window#79]
I use GNOME Wayland, and aw-watcher-window doesnt work on that, so I'm creating a simple GNOME extension that would get the active window title via GNOME's API, like in #46. The aw-client-js library can't be easily used in GJS, so the actual watcher will be made in Python and communitcate with the extension via D-Bus.

However, the question is, is it possible for users to replace aw-watcher-window? What I mean is some sort of a config to prevent aw-watcher-window from starting automatically and starting a custom version (eg. aw-watcher-window-gnome) instead.

**Comment by flexagoon** [comment]
Oh, never mind. I found the `autostart_modules` option in the config.

**Comment by johan-bjareholt** [comment]
@flexagoon I've already tried this, the D-Bus API is locked down in newer versions of gnome-shell, so only the xdg-desktop-gnome process is allowed to talk with it unless you fork the code. https://github.com/flatpak/xdg-desktop-portal/issues/304#issuecomment-1288205595

Long-term the best solution is probably to make an xdg-desktop-portal PR with a suggestion on an API and an PR to xdg-portal-gnome with an prototype implementation and then discuss further from there.

**Comment by johan-bjareholt** [comment]
> However, the question is, is it possible for users to replace aw-watcher-window? What I mean is some sort of a config to prevent aw-watcher-window from starting automatically and starting a custom version (eg. aw-watcher-window-gnome) instead.

I've done this for about 2 years with aw-watcher-window-wayland for phosh based compositors, works very well.
https://github.com/activitywatch/aw-watcher-window-wayland

**Comment by flexagoon** [comment]
> the D-Bus API is locked down in newer versions of gnome-shell, so only the xdg-desktop-gnome process is allowed to talk with it unless you fork the code

@johan-bjareholt what do you mean? Other applications should be able to talk to D-Bus, otherwise there would be no point in D-Bus. And I'm not calling the "active window" API directly, I made an extension that wraps this in a different D-Bus query

**Comment by johan-bjareholt** [comment]
@flexagoon D-Bus is for inter process communication yes, but that does not mean that any application is allowed to talk to any D-Bus service due to security. And in this case, instead of using the normal D-Bus policyxml files for D-Bus permissions, they've hardcoded the permissions in the app so you can't change them without recompiling the app. The only process allowed to use the API is xdg-desktop-portal-gnome. This was stated in the link I sent earlier.

**Comment by johan-bjareholt** [comment]
> And I'm not calling the "active window" API directly, I made an extension that wraps this in a different D-Bus query

What do you mean exactly? Which API are you using then?

**Comment by flexagoon** [comment]
> What do you mean exactly? Which API are you using then?

@johan-bjareholt the active window API can't be called by other apps due to security, but it *can* be called by GNOME Shell extensions. Extensions can also define their own DBus schemas, and apply their own security policies to them. So you can create an extension that defines a DBus function which everyone can call, and when that function gets called the extension runs the active window api and returns the result of that.

**Comment by flexagoon** [comment]
Here's an example of an extension that exposes private APIs as public DBus queries

https://github.com/ickyicky/window-calls

**Comment by johan-bjareholt** [comment]
Aha, that makes sense!
I was a bit confused before when you were talking about D-Bus, as I was for some reason assuming that you meant the gnome-shell Introspection D-Bus interface. 

In that case why even make a new watcher, why not try to integrate it straight into aw-watcher-window?
Another option would be to implemented it into aw-watcher-window-wayland, then you would get AFK support as well and have a complete solution for GNOME under wayland (as I believe that gnome-shell implements the idle.xml wayland protocol, which aw-watcher-window-wayland uses). I could even implement the whole watcher part in aw-watcher-window-wayland if you want, as long as you implement the gnome-extension part as that's outside of my expertise.

**Comment by johan-bjareholt** [comment]
Another option would be to just skip implementing an extension completely, and just re-use the window-calls extension.

**Comment by flexagoon** [comment]
@johan-bjareholt I released aw-watcher-gnome here:

https://github.com/flexagoon/aw-watcher-gnome

**Comment by igorcafe** [comment]
no workaround on plasma yet, right?

**Comment by flexagoon** [comment]
> no workaround on plasma yet, right?

@igorcafe awatcher supports plasma

https://github.com/2e3s/awatcher
