### ISSUE TITLE
[Linux] Can I use hyprctl to support Hyprland

### ISSUE THREAD

**Issue by mayapony** [ActivityWatch/aw-watcher-window#91]
Hyprland is a dynamic tiling Wayland compositor based on wlroots, It provides hyprctl, If I can use hyprctl to get the class and title, can I implement support for hyprland

![image](https://github.com/ActivityWatch/aw-watcher-window/assets/62200137/f200bf2d-abbd-472f-a9c4-f16b210fefe7)

**Comment by johan-bjareholt** [comment]
If it's based on wlroots, it might not need to be supported at all. Just use aw-watcher-window-wayland instead.

**Comment by mayapony** [comment]
> 

oh thanks!
