### ISSUE TITLE
[Windows] Apps run in Administrator not got recorded

### ISSUE THREAD

**Issue by fifv** [ActivityWatch/aw-watcher-window#94]
I saw some vacancy on the timeline. 
![image](https://github.com/ActivityWatch/aw-watcher-window/assets/75289510/74ce43ab-0d1b-4bfb-88b5-f4b08ea6d39b)

After some tests I realized they are apps run as administrator (e.g. `Windows Terminal (Admin)`, `Process Hacker (Administrator)` ), which don't have any logs in the Raw Data.

I tried `12.2` and `12.3b15`, both the same.

I tried to set `Run As Administrator` in the properties of `aw-watcher-window.exe`, but it just fail to start by `aw-qt`

**Comment by ErikBjare** [comment]
Same bug as reported in https://github.com/ActivityWatch/activitywatch/issues/873

I really should fix this, but I don't have a Windows machine to test the fix, so might have to spin up a VM.
